### TENSOR IS A MODULE IN A PYTORCH

## PYTORCH CAN DO ALL THE FUNCTION AVAILBLE IN NUMPY 

## SOME RANDOM TRYOUT'S IN PYTORCH

In [4]:
import torch

In [5]:
a=torch.Tensor([1,2,3])
a

tensor([1., 2., 3.])

In [6]:
c=a*5
c

tensor([ 5., 10., 15.])

In [7]:
a.sum()

tensor(6.)

In [8]:
b=torch.rand(3,4)
b

tensor([[0.4072, 0.0692, 0.4341, 0.7024],
        [0.4036, 0.8913, 0.8549, 0.6337],
        [0.0367, 0.4168, 0.7567, 0.9116]])

In [14]:
mat_1=torch.rand(2,3)
mat_2=torch.rand(2,3)
res=mat_1*mat_2
res

tensor([[0.2935, 0.0996, 0.2064],
        [0.3549, 0.0239, 0.0524]])

In [17]:
a.shape



torch.Size([3])

In [19]:
a=torch.eye(5)
a.shape
#a.dtype

torch.Size([5, 5])

## SOME REAL STUFF

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import dataloader,TensorDataset

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
